name: Build Action

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "zulu"

      - name: Build project
        run: gradle shadowJar && gradle build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: MinecraftBOT
          path: ./build/libs/*.jar
          if-no-files-found: error
